CREATE TYPE "EmploymentType" AS ENUM ('FULL_TIME', 'PART_TIME', 'MINI_JOB');
CREATE TYPE "EmployeeRole" AS ENUM ('WAITER', 'RUNNER', 'BARTENDER');

ALTER TABLE "employees"
ADD COLUMN "first_name" TEXT NOT NULL DEFAULT '',
ADD COLUMN "last_name" TEXT NOT NULL DEFAULT '',
ADD COLUMN "email" TEXT NOT NULL DEFAULT '',
ADD COLUMN "phone" TEXT,
ADD COLUMN "employment_type" "EmploymentType" NOT NULL DEFAULT 'PART_TIME',
ADD COLUMN "employee_role" "EmployeeRole" NOT NULL DEFAULT 'WAITER',
ADD COLUMN "weekly_hour_limit" INTEGER NOT NULL DEFAULT 1,
ADD COLUMN "active" BOOLEAN NOT NULL DEFAULT true,
ADD COLUMN "created_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
ADD COLUMN "updated_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP;

CREATE UNIQUE INDEX "employees_email_key" ON "employees"("email");
