[build]
builder = "nixpacks"
buildCommand = "./mvnw clean package -DskipTests"

[deploy]
startCommand = "java -jar target/Schedule_Planner-0.0.1-SNAPSHOT.jar"
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 5
